### ISSUE TITLE
Define Image to share

### ISSUE THREAD

**Issue by xstable** [djds4rce/angular-socialshare#25]
Is there a way to define which image to share.
Normally it's may set with og:image - MetaTag. How can I set it with your script?

**Comment by djds4rce** [comment]
There was a way to set images to facebook share, but facebook no longer accepts it. There is no other way to do this than set og:image, But does to ajax nature of angular there can only be a site wide image and no images for individual routes. I suggest you create a server side solution for this i.e share of corresponding server side URL for that particular page which directs to the actual angular page but has the right meta tags. We tried this is in a old project of mine and it worked perfectly for all platforms.
