### ISSUE TITLE
Add ability to add them as icons with customization images

### ISSUE THREAD

**Issue by Robert-Leggett** [djds4rce/angular-socialshare#27]
Can you make the following directives:

twitter-share-icon
linkedin-share-icon
gplus-share-icon
yammer-share-icon
facebook-share-icon

That you simply have to add a class like, twitter, linkedin, gplus, yammer, facebook and in that need to override the background attribute to have a custom icon.

please check https://developers.google.com/+/web/share/#sharelink for icon examples.

please check https://about.yammer.com/yammer-blog/introducing-yammer-share-button-3/ and the screen show for a final state looking to achieve.

![share](https://cloud.githubusercontent.com/assets/6155814/6518385/ae7ed40a-c3f9-11e4-9394-db2476bccb1f.png)

**Comment by Robert-Leggett** [comment]
Hi,

Thanks, but don't worry about this request I found another angular library that does what I require.

Thanks

**Comment by xstable** [comment]
Which one?

**Comment by Robert-Leggett** [comment]
@xstable https://github.com/fixate/angular-social-links
