### ISSUE TITLE
Translate or add custom share text?

### ISSUE THREAD

**Issue by raphaelluchini** [djds4rce/angular-socialshare#31]
Would be great we be able to customise or get the share text translated from facebook automatically.

**Comment by djds4rce** [comment]
Explain more please. Not sure what exactly you want.

**Comment by raphaelluchini** [comment]
For example, using a default facebook button. If I load the sdk with a (specific language)[https://developers.facebook.com/docs/internationalization/] the text 'Share' is automatically translated.

Maybe there's a way to get the translation from sdk, (I don't know if it's possible), or a good option is create a parameter to set a custom text.

**Comment by infodark** [comment]
+1

**Comment by djds4rce** [comment]
I'll see what I can do

**Comment by klaoha06** [comment]
This plugin is great! however; i think i would be a good idea if the facebook directive takes in as its argument the url to share with no additional html or css add on to it at all .. and leave the styling up to the user. In my case, I already have the button created .. i just need the link which share it that url .. but now I have the extra the html and css which i do not need. 

BEFORE
![screen shot 2558-03-28 at 2 34 28 pm](https://cloud.githubusercontent.com/assets/7324927/6880191/d1405b84-d557-11e4-9aba-021481489f76.png)

AFTER
![screen shot 2558-03-28 at 2 34 07 pm](https://cloud.githubusercontent.com/assets/7324927/6880190/cca23c50-d557-11e4-8628-eb5c6518aab9.png)

**Comment by djds4rce** [comment]
@klaoha06  U can do that by overriding the template string in the directive.

**Comment by djds4rce** [comment]
Hey @klaoha06  You can overirde the template string by this method http://stackoverflow.com/a/26339919/398421

Cheers

**Comment by djds4rce** [comment]
#71  fixes the issue
