### ISSUE TITLE
error in 'Getting Started' Text

### ISSUE THREAD

**Issue by JoergPf** [djds4rce/angular-socialshare#32]
Hi, you write in Getting Started on the GitHub Landing Page
    ` <style rel='stylesheet' type='text/css' href="bower_components/angular-socialshare/angular-socialshare.min.css"></style>`

but shouldn't it be
     `<link rel='stylesheet' href="bower_components/angular-socialshare/angular-socialshare.min.css">`

?

**Comment by djds4rce** [comment]
Thanks
