### ISSUE TITLE
bower version

### ISSUE THREAD

**Issue by mistermicko** [djds4rce/angular-socialshare#35]
can you please update bower version of package. In bower latest available version is 0.0.7.

**Comment by djds4rce** [comment]
Here it says 1.2 https://github.com/djds4rce/angular-socialshare/blob/master/bower.json 

What do you mean? Please elaborate. Iam using bower for the first time.

**Comment by Burstaholic** [comment]
Maybe you missed my reply on my PR - looking at their docs, I suspect it is because that is the last tag you have which conforms to the http://semver.org/ spec (3 specifiers, not 2).

**Comment by djds4rce** [comment]
Thank you for this. Can you please tell me where i can test this? And what should be the exact change?

**Comment by Burstaholic** [comment]
I think tagging 1.3.0 will do it. `bower info angular-socialshare` should tell you if Bower is picking it up correctly.

It's good to distinguish 'patch' from 'minor' updates anyway, which I think the SemVer site explains pretty well.

**Comment by djds4rce** [comment]
I released a new tag https://github.com/djds4rce/angular-socialshare/releases/tag/1.3.0 Can you please check and let me know please? I  currently do not have access to the command line.

**Comment by Burstaholic** [comment]
Looks like it worked!

```
bower angular-socialshare#*   resolved git://github.com/djds4rce/angular-socialshare.git#1.3.0

{
  name: 'angular-socialshare',
  main: 'angular-socialshare.js',
  version: '1.3.0',
  authors: [
    'djds4rce <djd4rce@gmail.com>'
  ],
  description: 'Social Share buttons for AngularJS',
  keywords: [
    'social',
    'googleplus',
    'facebook',
    'twitter',
    'linkdin'
  ],
  license: 'MIT',
  ignore: [
    '**/.*',
    'node_modules',
    'bower_components',
    'test',
    'tests'
  ],
  homepage: 'https://github.com/djds4rce/angular-socialshare'
}

Available versions:
  - 1.3.0
  - 0.0.7
  - 0.0.6
  - 0.0.5
  - 0.0.4
  - 0.0.3
  - 0.0.2
  - 0.0.1
```

**Comment by djds4rce** [comment]
Thanks for the help mate :+1:
