### ISSUE TITLE
Dynamic value for twitter and facebook

### ISSUE THREAD

**Issue by scne** [djds4rce/angular-socialshare#37]
Hi guys, I would pass dynamic value to url for facebook e twitter share.
I've this code
```
<a facebook class="facebookShare" data-url='http://mysite.com/videos/{{video.id}}' data-shares='shares'>{{ shares }}</a>
<a twitter  data-lang="en" data-count='horizontal' ng-data-url='http:///mysite.com//videos/{{video.id}}' data-via='notsosleepy' data-size="medium" data-text='Testing Twitter Share' ></a>
```
Into tag a for twitter I'm using ng-data-url instead of data-url, but when I use this into facebook directive there is an error. There is any way to pass dynamic value to url?

**Comment by djds4rce** [comment]
Why are you using ng-data-url just data-url works. Make sure you are using a version above or equal to 1.0.

**Comment by scne** [comment]
Now I'm using 1.2 version and this code doesn't work 
```
<a facebook class="facebookShare" data-url='http://mysite.com/videos/{{video.id}}' data-shares='shares'>{{ shares }}</a>
<a twitter  data-lang="en" data-count='horizontal' ng-data-url='http:///mysite.com//videos/{{video.id}}' data-via='notsosleepy' data-size="medium" data-text='Testing Twitter Share' ></a>
```

**Comment by djds4rce** [comment]
Please remove the ng-data-url and use data-url and please give me a plunkr/jsbin of your code so i debug.

**Comment by scne** [comment]
Sorry man, I've edited my question. I'm not using ng-data-url.

**Comment by djds4rce** [comment]
http://plnkr.co/edit/Z06H2XQtl0T8UHbZmdHI?p=preview Here you go I have done what you want in this plunk its working perfectly for me. Closing this.
