### ISSUE TITLE
toString() error

### ISSUE THREAD

**Issue by mordecai87** [djds4rce/angular-socialshare#39]
Hi, I have an error that I cant understand. Here is my log:

TypeError: Cannot read property 'toString' of undefined
    at angular-socialshare.js:73
    at angular.min.js:80
    at angular.min.js:112
    at l.$eval (angular.min.js:125)
    at l.$digest (angular.min.js:122)
    at l.$apply (angular.min.js:126)
    at l (angular.min.js:81)
    at S (angular.min.js:85)
    at XMLHttpRequest.D.onload (angular.min.js:86)

I don't kwon how to resolve that, Is there a problem with angular-socialshare?

Thank you!

**Comment by djds4rce** [comment]
I have no access to my machine till Monday. I'll help you then. Sorry.

**Comment by Burstaholic** [comment]
That's in the Facebook API response parsing, so you might check what you're getting back from that Facebook call.

**Comment by mordecai87** [comment]
Probably I am not calling well The facebook Api. I am using the facebook javascript sdk, It can be a compatibility problem with angular? Because the app works well.. Thank you for all!

**Comment by djds4rce** [comment]
There is no compatibility issues.
Possible things you can check
1. Are you including the SDK URL?
2. Is your sharing URL local host? Then try with public accessible link
3.Put a debugger in the library code and see what response are you getting.

**Comment by chriseckman** [comment]
It's not parsing the xml correctly. 

If your using jQuery, this will work.

```
var xml = $(res),
xmlCount = xml.find('total_count');
var count = xmlCount.text();
```

**Comment by djds4rce** [comment]
Can you provide more info on where this fix needs to be present? So we can
fix it in the lib?

**Comment by chriseckman** [comment]
It was around line 138 in the unminified version. 

**var count = res[0] ? res[0].total_count.toString() : 0;**

**Comment by djds4rce** [comment]
This line requests the data in JSON I am not sure why we need to worry about XML. Are you still facing the issue?

> $http.get('https://api.facebook.com/method/links.getStats?urls=' + attr.url + '&format=json')
