### ISSUE TITLE
Get callback when user shares something

### ISSUE THREAD

**Issue by alexislg2** [djds4rce/angular-socialshare#43]
Hey
thanks for your great plugin. I'ld like to have a callback triggered when the user shares a URL. How can I do that?

Thanks

**Comment by djds4rce** [comment]
Hey thanks for the kind words. What exactly do you want to do? I am not
sure about the callback. It is mostly not possible. But I will find out and
update it.

**Comment by alexislg2** [comment]
I'm developing a game. I want to give a reward when the player share some URLs on FB.

**Comment by djds4rce** [comment]
I will get back to you over the weekend

**Comment by djds4rce** [comment]
I am Afraid there is no way to do this. Have a look at
https://developers.facebook.com/docs/reference/javascript/FB.Event.subscribe/v2.4
no event for link sharing.

**Comment by djds4rce** [comment]
Hey I was sleepy and exhausted the last time I checked, look what I found today 
```
FB.ui(
  {
    method: 'share',
    href: 'https://developers.facebook.com/docs/',
  },
  // callback
  function(response) {
    if (response && !response.error_message) {
      alert('Posting completed.');
    } else {
      alert('Error while posting.');
    }
  }
);
```

I will write add a feature pretty soon where you can add a callback. Hope its not too late yet.

**Comment by alexislg2** [comment]
Thank you very much
I'm afraid this callback might be called also when the user cancel the
share operation...

**Comment by djds4rce** [comment]
Yes but your response object will point to whether it is shared or not so you must be good to go.
