### ISSUE TITLE
Facebook share overridden

### ISSUE THREAD

**Issue by moioo91120** [djds4rce/angular-socialshare#47]
Hello,

I love your directive, it sounds really good.

However, whenever I try to use share a page on facebook, data-url, data-title ... are being ignored and the directive try to share the root url of the website.

In my page, I use some meta informations, like meta title, description, keywords ... Maybe it's interfering with the directive.

Any idea? 

Thanks

**Comment by djds4rce** [comment]
Are you sharing a localhost url? It doesnt work sometime

**Comment by moioo91120** [comment]
Thank you for the quick reply.

I'm sharing on my website, https://www.gameofphone.com/collection/mousse-cat-tower

Compiled version of the directive is 
<div class="facebookShare ng-isolate-scope" data-shares="shares" data-url="https://www.gameofphone.com/collection/mousse-cat-tower" data-picture-url="https://mage.gameofphone.com/media/catalog/product/d/s/dsc06136_1.jpg" data-title="Cat tower - Karakuti Mousse" facebook="">

Which looks pretty good.

But whenever I try to share, it only shares the root url : www.gameofphone.com

**Comment by djds4rce** [comment]
Share your code please

**Comment by moioo91120** [comment]
div 	facebook class="facebookShare" 
							data-title="{{ $state.current.title}}" 	
							data-picture-url="{{product.largeImage}}" 
							data-url="{{ location.absUrl()}}" 
							data-shares='shares'>{{ shares }}
					</div>

**Comment by moioo91120** [comment]
And in the Application.js file : 

moaApp.run(function($FB){
	$FB.init('1644044445869059');
});

**Comment by djds4rce** [comment]
There seems to be no problem with the directive. This is the URL which is being redirected to in the popup window. Also I am really sorry but Facebook no longer takes in meta data hence your picture and title does not work. 

https://www.facebook.com/dialog/share?app_id=1644044445869059&display=popup&e2e={}&href=https://www.gameofphone.com/collection/mousse-cat-tower&locale=en_US&next=https://s-static.ak.facebook.com/connect/xd_arbiter/YKPvjVoWVGb.js?version=41#cb=f263686e84&domain=www.gameofphone.com&origin=https%3A%2F%2Fwww.gameofphone.com%2Ff3389cafdc&relation=opener&frame=f9c2bce24&result=%22xxRESULTTOKENxx%22&sdk=joey
