### ISSUE TITLE
Doesn't work on device

### ISSUE THREAD

**Issue by ShrinivasKattimani** [djds4rce/angular-socialshare#48]
Hi,
I am developing a hybrid application, which needs social sharing. I tried with facebook sharing and it doesn't work. Nothing happens when I tap on share button. However, when I run on browser, I get this error: 
'Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.'

Any suggestions?

**Comment by djds4rce** [comment]
The URL you are testing on isn't added in the Facebook app URL. Not sure
what URL must be added for testing on hybrid app.
