### ISSUE TITLE
Twitter button not coming in firefox

### ISSUE THREAD

**Issue by gautam-bst** [djds4rce/angular-socialshare#52]
Hey
First of all, thanks for such a great plugin. The plugin runs smoothly in chrome, but for some reasons the tweet button is not coming in firefox, the version I am using is 41.0.2. I can see the iframe in the page source, but their's visibility is set to hidden and height/width is set to 0.

The developers community of twitter says that it should work on firefox 36+.

Any ideas, why it isn't working..?

Thanks
Gautam Pahuja

**Comment by djds4rce** [comment]
Must be a browser issue. I will look into it and let you know

**Comment by djds4rce** [comment]
not able to download firefox on my system due to some corporate settings. Will try to fix this when i get my hands on a machine where i can download firefox.

**Comment by djds4rce** [comment]
I also used browserstack to test it on  FF 42 and it works. Free version of Browser stack does not support firefox < than 42. Not sure what the issue is.

**Comment by atefBB** [comment]
Hey, I'm using firefox 53.0.2 (32 bits) on win7, and I have the same issue, any ideas how to fix it?
(sorry to comment in a closed issue one year ago)

**Comment by djds4rce** [comment]
Please help me reproduce this issue.

**Comment by atefBB** [comment]
this my code : 
`<a twitter data-lang="{{ my_app_active_language }}" data-count="horizontal" data-url="https://www.mywebsite.com" data-size="medium" data-text="{{ my_social_share_text }}"></a>`.
wish it help!
