### ISSUE TITLE
Syntax error on package.json

### ISSUE THREAD

**Issue by filipesilva** [djds4rce/angular-socialshare#53]
Heya,

On the version downloaded by bower there is still a syntax error on `package.json` (mismatched `"`)

```
"version": "1.4.2,
```

I noticed it is fixed in the source code, but since it's not on the release then bower downloads the wrong one. In my specific case, I'm loading this package via webpack, and it doesn't even allow me to load anything there since `package.json` is invalid.

(as a side-note, version should also be 1.4.3)

Cheers

**Comment by djds4rce** [comment]
I am really sorry for your error. I have never used package.json hence this mistake. Will fix it immediately and make sure will not happen again. Thank you for your heads up :+1:

**Comment by filipesilva** [comment]
Cheers for the speedy fix!
