### ISSUE TITLE
Remove Share Count?

### ISSUE THREAD

**Issue by iamchairs** [djds4rce/angular-socialshare#55]
I don't want share counts on my buttons. How can I remove them?

**Comment by djds4rce** [comment]
You can only override templates of facebook and linkedin directives(Using This http://stackoverflow.com/questions/17660947/can-you-override-specific-templates-in-angularui-bootstrap). You cannot override Twitter and google plus. I would suggest to not use this as this directive is written with counts being shown in Mind. Instead you can use a ng-click and trigger opening of share url of individual social networks in a  new window. For example Linkdin Share would do something like 
````
$window.open("//www.linkedin.com/shareArticle?mini=true&url=" + url + "&title=" + attr.title + "&summary=" + attr.summary);
```

This is a valid way for implementing share button but without a count.
