### ISSUE TITLE
Custom Icons

### ISSUE THREAD

**Issue by romin4you** [djds4rce/angular-socialshare#56]
I am working on a project which has it's own custom icons for social sharing. But most of your code is about pulling iframes. you should add feature for custom icons.

**Comment by djds4rce** [comment]
You can rewrite the template for linkdin and facebook directives http://stackoverflow.com/questions/17660947/can-you-override-specific-templates-in-angularui-bootstrap. But you cannot do it for the rest and the providers do not let you override it. This directive is more concerned about share counts than custom style. If you need custom styles you can use a ng-click and trigger opening of share url of individual social networks in a new window. For example Linkdin Share would do something like
````
$window.open("//www.linkedin.com/shareArticle?mini=true&url=" + url + "&title=" + attr.title + "&summary=" + attr.summary);
````

This is a valid way for implementing share button but without a count.
