### ISSUE TITLE
Uncaught ReferenceError: FB is not defined

### ISSUE THREAD

**Issue by khwerhahn** [djds4rce/angular-socialshare#57]
Hi,

when I click on the Facebook share button the console spits out: "Uncaught ReferenceError: FB is not defined"...

What am I doing wrong?

**Comment by djds4rce** [comment]
Are you including the facebook SDK?

**Comment by djds4rce** [comment]
Sorry the facebook SDK is not needed or you setting the Facebook App ID?

**Comment by Lazarencjusz** [comment]
Refresh, I have same problem. "Uncaught ReferenceError: FB is not defined"

**Comment by djds4rce** [comment]
Include the fb SDK. But that is not the problem for sure

**Comment by Lazarencjusz** [comment]
Problem appears in google chrome:
XMLHttpRequest cannot load https://api.facebook.com/method/links.getStats?urls=http://boardgameme.pl&format=json. The request was redirected to a URL ('about:blank') which has a disallowed scheme for cross-origin requests.
after click share:
angular-socialshare.min.js:1 Uncaught ReferenceError: FB is not defined
Opera and Firefox works

**Comment by Lazarencjusz** [comment]
Problem appears in google chrome:
XMLHttpRequest cannot load https://api.facebook.com/method/links.getStats?urls=http://google.pl&format=json. The request was redirected to a URL ('about:blank') which has a disallowed scheme for cross-origin requests.
after click share:
angular-socialshare.min.js:1 Uncaught ReferenceError: FB is not defined
Opera and Firefox works

**Comment by djds4rce** [comment]
Can you please try reproducing the Issue in JSBin? I will try my best to solve it from there
