### ISSUE TITLE
Can I customize the style of the difrents buttons (Twitter, facebook, linkedin, etc)

### ISSUE THREAD

**Issue by ignacio-chiazzo** [djds4rce/angular-socialshare#58]
Is there a way to change the style of the buttons of the different social networks?

**Comment by djds4rce** [comment]
You can change style for fb and LinkedIn. Rest of the buttons use default
styles.
https://github.com/djds4rce/angular-socialshare/blob/master/angular-socialshare.less.
#closed

**Comment by ignacio-chiazzo** [comment]
I cannot edit the button of Twitter? I can believe it.

**Comment by djds4rce** [comment]
Iam sorry but this plugin was written with share count retrival as primary
objective hence flexibility of styling had been sacrificed where needed. If
styling is your primary goal there are other plugins which do that.

**Comment by ignacio-chiazzo** [comment]
@djds4rce  ok, but why not changing the code ? maybe you can keep both

**Comment by djds4rce** [comment]
Thanks for the idea but I would pass. There already are projects which do
this
