### ISSUE TITLE
Integrate with Cordova / Phonegap

### ISSUE THREAD

**Issue by davibertolini** [djds4rce/angular-socialshare#65]
Hi! I've been trying to use the angular-socialshare on a Phonegap / Cordova (v. 6.0.0) app on iOS.

When clicking on the button 

`<a facebook role="button" class="btn btn-fb btn-lg center-block" data-url="https://URL_TO_REST_SERVICE/shareOnFB?token_auth={{getTokenAuth()}}&uid={{getTransactionId()}}&format=html">Share on Facebook</a>`

Won't do anything. No errors on console.

Any suggestions?

**Comment by djds4rce** [comment]
Ideally it should never cause a problem. Have you done all settings right?

**Comment by davibertolini** [comment]
It is working on web applications hosted in our production and dev servers. But when either launching the app on an iOS device with `# phonegap serve` or launching it on the iOS simulator (Xcode), it won't work (i.e. it won't do anything) and no messages are shown in the log (e.g. I could expect a "cross domain error" or a "$FB not found").

**Comment by djds4rce** [comment]
$FB needs a domain to initialize. Cordova serves it in the local domain.
For sharing you will have to use different Cordova bridge
https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin

**Comment by davibertolini** [comment]
Can I leverage somehow the SafariView or in app browser with your plugin?

**Comment by djds4rce** [comment]
If you load an external URL like http://example.com it will
work(theoretically). Loading from local Cordova serve will not work
