### ISSUE TITLE
Cannot read property 'appendChild' of null in twitter widgets.js

### ISSUE THREAD

**Issue by deepaksaini6413** [djds4rce/angular-socialshare#68]
Hello,
I integrated this code everything working fine, but 1 error is showing in console that "Cannot read property 'appendChild' of null " in twitter widgets.js. I am following the same instruction as you mentioned in your documents.

**Comment by djds4rce** [comment]
Can you reproduce it in jsbin or elsewhere please?

**Comment by djds4rce** [comment]
Not enough Info
