### ISSUE TITLE
Pressing Post or Cancel Shows X-Frame-Options Error

### ISSUE THREAD

**Issue by psmod2** [djds4rce/angular-socialshare#69]
Hi,

I've got a facebook-feed-share button however whenever I click on Cancel or Post on the popup I get the error:

Refused to display 'https://www.facebook.com/common/invalid_request.php' in a frame because it set 'X-Frame-Options' to 'DENY'.

The frame just goes blank and remains on the screen.

Any ideas on how to fix this?

Thanks.

**Comment by djds4rce** [comment]
Have you set the right app ID in the settings and is the URL in Facebook
developers app setting?

**Comment by psmod2** [comment]
Yes I have it defined:

.run(function($FB){
  $FB.init('105xxxxxxxx36');
})

**Comment by djds4rce** [comment]
Just check if it's the right app.ID corresponding  to the app URL.

**Comment by psmod2** [comment]
App.ID and App URL are 100% correct - should it appear as an iFrame, is it possible to say appear as a popup instead? I think that would solve my issue

**Comment by djds4rce** [comment]
Can you try that? Iam yet to get my hands on a PC to test this.

**Comment by djds4rce** [comment]
Hey Does this link help by any chance? http://stackoverflow.com/questions/23555592/refused-to-display-in-a-frame-because-it-set-x-frame-options-to-deny-facebook

**Comment by psmod2** [comment]
Hi,

I tried using "target:_top" however that didn't help.

As I'm only using Facebook share I ended up using their implementation directly.

Thanks for your help though.
