### ISSUE TITLE
Possible malware code in this library?

### ISSUE THREAD

**Issue by FranciZ** [djds4rce/angular-socialshare#73]
I'm busting my head how is it possible that an advertisement link gets injected into the share and I'm just concerned that malicious code has been packaged in to the .min script of this library. Better safe than sorry.

<img width="731" alt="screen shot 2016-11-21 at 17 25 05" src="https://cloud.githubusercontent.com/assets/2536035/20490891/d7ede4da-b00f-11e6-8380-3a9e411d02d7.png">

**Comment by djds4rce** [comment]
Just looked at the minified code. Can't seem to find any problems. Iam away
from PC till next Monday. Is it possible for you to spend some time on it?

**Comment by FranciZ** [comment]
I'm already on it, can't find anything at the moment. I was able to consistently replicate the problem though on multiple systems and deployments.

**Comment by djds4rce** [comment]
Can you try reproducing it In the demo plunker by forking it?

**Comment by FranciZ** [comment]
Ok, it might not be an issue with the library. Our client seems to be doing something non standard which might be the cause for this. I've seen malicious code accidentally merged into production so I'd rather be safe than sorry when letting others know.  I'm super grateful for the fast response, and sorry to have wasted your time.

**Comment by djds4rce** [comment]
Thanks for letting me know :) #closed open if needed.
