### ISSUE TITLE
Outdated API used to get stats from Facebook. 

### ISSUE THREAD

**Issue by ravimallya** [djds4rce/angular-socialshare#74]
I'm receiving the following error either when using facebook share or facebook feed share button in console and share counts are not getting updated.

> XMLHttpRequest cannot load https://api.facebook.com/method/links.getStats?urls=http://www.onlinecmr.in…hina-cuts-corn-surplus-estimate-on-higher-demand-lower-imports&format=json. Request header field API_KEY is not allowed by Access-Control-Allow-Headers in preflight response.

I thought it might because of the changeset https://github.com/djds4rce/angular-socialshare/pull/72 . Digging further landed up in the SO question at: http://stackoverflow.com/questions/39028734/get-facebook-share-like-comment-count-of-url , http://stackoverflow.com/questions/37491742/getting-facebook-share-like-and-comment-counts-for-a-given-url-with-api-graph-v and noticed the following in directive:

```
$http.get('https://api.facebook.com/method/links.getStats?urls=' + attr.url + '&format=json', {withCredentials: false}).success(function(res) {
 // success callback goes here
})
```
Here, what and all we've to send using new FQL to get counts? How it can be fixed?

**Comment by djds4rce** [comment]
Ill have to look through the fql changes and see how to fix it

**Comment by djds4rce** [comment]
Found a workaround url for this to work

**Comment by atefBB** [comment]
@djds4rce I have the same issue, so how to fix it?

**Comment by djds4rce** [comment]
You need to change the API endpoint used to fetch the fb share count

**Comment by atefBB** [comment]
you mean something like this: <br>
`https://graph.facebook.com/v2.7?emc=rss&fields=og_object{engagement},share&access_token=<ACCESS_TOKEN_GOES_HERE>&id=http://stackoverflow.com/`

**Comment by djds4rce** [comment]
Yes

On Sep 27, 2017 12:12 PM, "Atef Ben Ali" <notifications@github.com> wrote:

you mean something like this:

https://graph.facebook.com/v2.7?emc=rss&fields=og_object{
engagement},share&access_token=<ACCESS_TOKEN_GOES_HERE>&id=
http://stackoverflow.com/

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/djds4rce/angular-socialshare/issues/74#issuecomment-332424716>,
or mute the thread
