### ISSUE TITLE
This is great however I think it is outdated...

### ISSUE THREAD

**Issue by gmarshall56** [djds4rce/angular-socialshare#75]
I'm getting this when the call to api.facebook is made:

{"error_code":12,"error_msg":"REST API is deprecated for versions v2.1 and higher (12)","request_args":[{"key":"method","value":"links.getStats"},{"key":"urls","value":"www.mpi-mps.org"},{"key":"format","value":"json"}]}

?????

**Comment by djds4rce** [comment]
Iam sorry I have been busy. I will fix it soon

**Comment by djds4rce** [comment]
Found a work around and now this works
