### ISSUE TITLE
Twitter not show count data.

### ISSUE THREAD

**Issue by pajingko** [djds4rce/angular-socialshare#79]
My code is below.

`<a twitter  data-lang="en" data-count='horizontal' data-url='{{shareUrl}}' data-size="medium" data-text='Tweet' ></a>`

Tweet count data not show.

**Comment by djds4rce** [comment]
is it being tested on local host?

**Comment by pajingko** [comment]
Thanks for reply. Twitter count share data is no longer after 20th Nov. 2015.
